spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "147728776223-rs7s2bkionkf3pc5d995c71o64qmhalf.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile
              - openid