CREATE TABLE token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    token_value VARCHAR(1024),
    token_type  VARCHAR(255),
    expires_at  TIMESTAMP WITHOUT TIME ZONE,
    revoked     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

CREATE INDEX idx_token_value ON token (token_value);

ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);